<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>foundryfriend</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Inference" Version="1.0.0-beta.5" />
    <PackageReference Include="Azure.AI.Projects" Version="2.1.0-beta.1" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Figgle" Version="0.6.6" />
    <PackageReference Include="Figgle.Fonts" Version="0.6.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="System.CommandLine" Version="2.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FoundryFriend.Core\FoundryFriend.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="AgentSamples\customer-support.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AgentSamples\math-tutor.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AgentSamples\doc-u-wan.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AgentSamples\ms-learn-assistant.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
